### ISSUE TITLE
A3AA update breaking the Coop/PvP modules

### ISSUE THREAD

**Issue by CNTODachi** [CntoDev/compositions#100]
Due to the update, the following will break within the default module compositions and need replacing:

- [x] Replace the Arsenal Respawn module.

- [x] Replace the Basic Vehicle cargo module.

- [x] Replace the Briefing (OPORD) module.

- [x] Replace the local transfer (to HC) module.

- [x] Replace the execute code module disabling in-game text channels.

- [x] Replace the execute code module for multiplayer settings. Coop, Coop No Respawn and PvP.

**Comment by JamesTheClarke** [comment]
I believe the one-life module has also been updated either in the current version or the upcoming one. Might wanna double check just to be sure.
