### ISSUE TITLE
TFN Vehicle Camo Modules do not work.

### ISSUE THREAD

**Issue by Seb105** [CntoDev/compositions#102]
Whilst updating camo modules to the new version of arma additions, I noticed execute code vehicle camo modules weren't working. 

Assuming the upgrade had broken them I tried them on the old version. There they do not work either, so it is not an problem with the new version of Arma Additions.

Executing the code manually via debug does nothing, but does not produce a script error.

This must've broken at some point in the past and gone unnoticed until now. 

The last time I used them was Oct 4 2019, and they worked back then.

This code makes use of CBA functions, maybe them updating broke it.

**Comment by Seb105** [comment]
Not working code:

`TFN_DESERT_VEHICLES:

{
    [_x, "InitPost", {
        params ["_unit"];
        _unit setObjectTexture [0, "cnto\assets\dc_strider\hull_desert.paa"];
        _unit setObjectTexture [1, "cnto\assets\dc_strider\turret_desert.paa"];
    }] call CBA_fnc_addClassEventHandler;
} forEach ["I_MRAP_03_F", "I_MRAP_03_gmg_F", "I_MRAP_03_hmg_F"];

["I_MBT_03_cannon_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_kuma\hull_desert.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_kuma\gun_desert.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_kuma\turret_desert.paa"];
}] call CBA_fnc_addClassEventHandler;

["O_APC_Wheeled_02_rcws_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_marid\hull_desert.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_marid\wheels.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_marid\turret_desert.paa"];
}] call CBA_fnc_addClassEventHandler;

["I_Heli_Transport_02_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_mohawk\cnto_mohawk_1_hull.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_mohawk\cnto_mohawk_2_tail_ins.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_mohawk\cnto_mohawk_3_rotor_top.paa"];
}] call CBA_fnc_addClassEventHandler;  

{
    [_x, "InitPost", {
        params ["_unit"];
        _unit setObjectTexture [0, "cnto\assets\dc_hellcat\cnto_hellcat.paa"];
    }] call CBA_fnc_addClassEventHandler;
} forEach ["I_Heli_light_03_dynamicLoadout_F","I_Heli_light_03_unarmed_F"];

TFN_FOREST_VEHICLES:

{
    [_x, "InitPost", {
        params ["_unit"];
        _unit setObjectTexture [0, "cnto\assets\dc_strider\hull_forest.paa"];
        _unit setObjectTexture [1, "cnto\assets\dc_strider\turret_forest.paa"];
    }] call CBA_fnc_addClassEventHandler;
} forEach ["I_MRAP_03_F", "I_MRAP_03_gmg_F", "I_MRAP_03_hmg_F"];

["I_MBT_03_cannon_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_kuma\hull_forest.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_kuma\gun_forest.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_kuma\turret_forest.paa"];
}] call CBA_fnc_addClassEventHandler;

["O_APC_Wheeled_02_rcws_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_marid\hull_forest.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_marid\wheels.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_marid\turret_forest.paa"];
}] call CBA_fnc_addClassEventHandler;

["I_Heli_Transport_02_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_mohawk\cnto_mohawk_1_hull.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_mohawk\cnto_mohawk_2_tail_ins.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_mohawk\cnto_mohawk_3_rotor_top.paa"];
}] call CBA_fnc_addClassEventHandler;

{
    [_x, "InitPost", {
        params ["_unit"];
        _unit setObjectTexture [0, "cnto\assets\dc_hellcat\cnto_hellcat.paa"];
    }] call CBA_fnc_addClassEventHandler;
} forEach ["I_Heli_light_03_dynamicLoadout_F","I_Heli_light_03_unarmed_F"];

TFN_JUNGLE_VEHICLES:

{
    [_x, "InitPost", {
        params ["_unit"];
        _unit setObjectTexture [0, "cnto\assets\dc_strider\hull_jungle.paa"];
        _unit setObjectTexture [1, "cnto\assets\dc_strider\turret_jungle.paa"];
    }] call CBA_fnc_addClassEventHandler;
} forEach ["I_MRAP_03_F", "I_MRAP_03_gmg_F", "I_MRAP_03_hmg_F"];

["I_MBT_03_cannon_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_kuma\hull_jungle.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_kuma\gun_jungle.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_kuma\turret_jungle.paa"];
}] call CBA_fnc_addClassEventHandler;

["O_APC_Wheeled_02_rcws_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_marid\hull_jungle.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_marid\wheels.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_marid\turret_jungle.paa"];
}] call CBA_fnc_addClassEventHandler;

["I_Heli_Transport_02_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_mohawk\cnto_mohawk_1_hull.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_mohawk\cnto_mohawk_2_tail_ins.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_mohawk\cnto_mohawk_3_rotor_top.paa"];
}] call CBA_fnc_addClassEventHandler;

{
    [_x, "InitPost", {
        params ["_unit"];
        _unit setObjectTexture [0, "cnto\assets\dc_hellcat\cnto_hellcat.paa"];
    }] call CBA_fnc_addClassEventHandler;
} forEach ["I_Heli_light_03_dynamicLoadout_F","I_Heli_light_03_unarmed_F"];

TFN_GRASSLAND_VEHICLES

{
    [_x, "InitPost", {
        params ["_unit"];
        _unit setObjectTexture [0, "cnto\assets\dc_strider\hull_grassland.paa"];
        _unit setObjectTexture [1, "cnto\assets\dc_strider\turret_grassland.paa"];
    }] call CBA_fnc_addClassEventHandler;
} forEach ["I_MRAP_03_F", "I_MRAP_03_gmg_F", "I_MRAP_03_hmg_F"];

["I_MBT_03_cannon_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_kuma\hull_grassland.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_kuma\gun_grassland.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_kuma\turret_grassland.paa"];
}] call CBA_fnc_addClassEventHandler;

["O_APC_Wheeled_02_rcws_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_marid\hull_grassland.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_marid\wheels.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_marid\turret_grassland.paa"];
}] call CBA_fnc_addClassEventHandler;

["I_Heli_Transport_02_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_mohawk\cnto_mohawk_1_hull.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_mohawk\cnto_mohawk_2_tail_ins.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_mohawk\cnto_mohawk_3_rotor_top.paa"];
}] call CBA_fnc_addClassEventHandler;

{
    [_x, "InitPost", {
        params ["_unit"];
        _unit setObjectTexture [0, "cnto\assets\dc_hellcat\cnto_hellcat.paa"];
    }] call CBA_fnc_addClassEventHandler;
} forEach ["I_Heli_light_03_dynamicLoadout_F","I_Heli_light_03_unarmed_F"];

TFN_SNOW_VEHICLES

{
    [_x, "InitPost", {
        params ["_unit"];
        _unit setObjectTexture [0, "cnto\assets\dc_strider\hull_snow.paa"];
        _unit setObjectTexture [1, "cnto\assets\dc_strider\turret_snow.paa"];
    }] call CBA_fnc_addClassEventHandler;
} forEach ["I_MRAP_03_F", "I_MRAP_03_gmg_F", "I_MRAP_03_hmg_F"];

["I_MBT_03_cannon_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_kuma\hull_snow.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_kuma\gun_snow.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_kuma\turret_snow.paa"];
}] call CBA_fnc_addClassEventHandler;

["I_APC_tracked_03_cannon_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_mora\gun_white.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_mora\hull_white.paa"];
}] call CBA_fnc_addClassEventHandler;

["O_APC_Wheeled_02_rcws_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_marid\hull_snow.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_marid\wheels.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_marid\turret_snow.paa"];
}] call CBA_fnc_addClassEventHandler;

["I_Heli_Transport_02_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_mohawk\cnto_mohawk_1_hull.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_mohawk\cnto_mohawk_2_tail_ins.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_mohawk\cnto_mohawk_3_rotor_top.paa"];
}] call CBA_fnc_addClassEventHandler;

{
    [_x, "InitPost", {
        params ["_unit"];
        _unit setObjectTexture [0, "cnto\assets\dc_hellcat\cnto_hellcat.paa"];
    }] call CBA_fnc_addClassEventHandler;
} forEach ["I_Heli_light_03_dynamicLoadout_F","I_Heli_light_03_unarmed_F"];

TFN_MEDI_VEHICLES

{
    [_x, "InitPost", {
        params ["_unit"];
        _unit setObjectTexture [0, "cnto\assets\dc_strider\hull_desert.paa"];
        _unit setObjectTexture [1, "cnto\assets\dc_strider\turret_desert.paa"];
    }] call CBA_fnc_addClassEventHandler;
} forEach ["I_MRAP_03_F", "I_MRAP_03_gmg_F", "I_MRAP_03_hmg_F"];

["I_MBT_03_cannon_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_kuma\hull_desert.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_kuma\gun_desert.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_kuma\turret_desert.paa"];
}] call CBA_fnc_addClassEventHandler;

["O_APC_Wheeled_02_rcws_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_marid\hull_desert.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_marid\wheels.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_marid\turret_desert.paa"];
}] call CBA_fnc_addClassEventHandler;

["I_Heli_Transport_02_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_mohawk\cnto_mohawk_1_hull.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_mohawk\cnto_mohawk_2_tail_ins.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_mohawk\cnto_mohawk_3_rotor_top.paa"];
}] call CBA_fnc_addClassEventHandler;

{
    [_x, "InitPost", {
        params ["_unit"];
        _unit setObjectTexture [0, "cnto\assets\dc_hellcat\cnto_hellcat.paa"];
    }] call CBA_fnc_addClassEventHandler;
} forEach ["I_Heli_light_03_dynamicLoadout_F","I_Heli_light_03_unarmed_F"];

TFN_URBAN_VEHICLES

{
    [_x, "InitPost", {
        params ["_unit"];
        _unit setObjectTexture [0, "cnto\assets\dc_strider\hull_grassland.paa"];
        _unit setObjectTexture [1, "cnto\assets\dc_strider\turret_grassland.paa"];
    }] call CBA_fnc_addClassEventHandler;
} forEach ["I_MRAP_03_F", "I_MRAP_03_gmg_F", "I_MRAP_03_hmg_F"];

["I_MBT_03_cannon_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_kuma\hull_grassland.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_kuma\gun_grassland.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_kuma\turret_grassland.paa"];
}] call CBA_fnc_addClassEventHandler;

["O_APC_Wheeled_02_rcws_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_marid\hull_grassland.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_marid\wheels.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_marid\turret_grassland.paa"];
}] call CBA_fnc_addClassEventHandler;

["I_Heli_Transport_02_F", "InitPost", {
    params ["_unit"];
    _unit setObjectTexture [0, "cnto\assets\dc_mohawk\cnto_mohawk_1_hull.paa"];
    _unit setObjectTexture [1, "cnto\assets\dc_mohawk\cnto_mohawk_2_tail_ins.paa"];
    _unit setObjectTexture [2, "cnto\assets\dc_mohawk\cnto_mohawk_3_rotor_top.paa"];
}] call CBA_fnc_addClassEventHandler;

{
    [_x, "InitPost", {
        params ["_unit"];
        _unit setObjectTexture [0, "cnto\assets\dc_hellcat\cnto_hellcat.paa"];
    }] call CBA_fnc_addClassEventHandler;
} forEach ["I_Heli_light_03_dynamicLoadout_F","I_Heli_light_03_unarmed_F"];
`

**Comment by JamesTheClarke** [comment]
Yeah, the TFN vehicle camo modules have been broken for a few months now. I've just included them as part of the TFN infantry camo modules in the hopes somebody would fix them down the line or I'll figure out how to do it myself.

**Comment by Seb105** [comment]
I'll take a look at some point, but there's more important things right now.

**Comment by JamesTheClarke** [comment]
Yeah fully agreed, time invested VS functionality gained is not worth prioritising atm.

**Comment by Seb105** [comment]
So I was working on an old mission that used this modules and it still worked... the code was exactly the same though, so I did some digging and have found

The camo modules _do_ work, but **only if our default modules are already placed down.**


Why? Idk.

**Comment by JamesTheClarke** [comment]
@Seb105 If I remember correctly you figured out a way to make them work. Could you please post a short step by step tutorial on how to do it? Then we can close this issue for good. :)

**Comment by Seb105** [comment]
It's literally the comment above. They work sometimes, and not others. I don't know why.

**Comment by Seb105** [comment]
Ok I may have figured it out, I'm not sure though

If the execute code module initialises after the vehicles, it will not work. The reason for this it uses "initPost", which is fine, but does not apply retroactively unless instructed to.

https://github.com/CBATeam/CBA_A3/wiki/Adding-Event-Handlers-to-Classes-of-Objects

There is an apply retroactively parameter of the add class event handler function which is by default false if not defined. Setting this to true could solve our issues

**Comment by milivojm** [comment]
Fixed by converting "InitPost" to "init" class event handler. It's not a CBA issue because it works if you copy/paste code to init.sqf script.

Beware, some vehicles are still missing textures.

**Comment by Seb105** [comment]
Test comment

**Comment by JamesTheClarke** [comment]
If this is fixed via PR #102 please close this issue @milivojm
