### ISSUE TITLE
Remove NiArms G36 and MG3 assets from TFN

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#106]
Due to adopting BW mod and subsequently removing duplicate NiArms mods the TFN faction will need to be adapted to exclude any NiArms G36 or MG3 assets.

https://www.carpenoctem.co/forums/m/26081621/viewthread/33263020-bw-modrepo-clean-up

**Comment by JamesTheClarke** [comment]
The issue also applies to 4th Standard Faction PMC to a degree.

**Comment by Seb105** [comment]
Done for TFN and PMC faction in this branch: https://github.com/CntoDev/compositions/tree/Standard-Factions-1.14.2
