### ISSUE TITLE
1x epinephrine for each soldier

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#107]
According to the July Monthly Meeting, it was decided to add 1x epi to each playable class. This change has to be implemented across all four standard factions and will need to be checked for custom factions going forward.

https://docs.google.com/document/d/1Lo6ssP8tul8LLI_iXvHhAnAQ2Xm6CpKbY3I7-2VekwU/edit#heading=h.8xxw6ujw21gl

**Comment by Seb105** [comment]
Done for TFN and PMC faction in this branch: https://github.com/CntoDev/compositions/tree/Standard-Factions-1.14.2

**Comment by JamesTheClarke** [comment]
Implemented for [Russian Army draft v.1.14.2](/CntoDev/compositions/tree/Russian-Standard-Faction-Update-v1.14.2)

**Comment by JamesTheClarke** [comment]
Implemented for [US Army v.1.14.2](/CntoDev/compositions/tree/US-Army-Standard-Faction-Update-v1.14.2)
