### ISSUE TITLE
Russian Army: AKS-74U cannot equip any scopes

### ISSUE THREAD

**Issue by Seb105** [CntoDev/compositions#108]
AKS-74UN can, looks and performs identically.

Suggest find & replace "rhs_weap_aks74u" in sqm with "rhs_weap_aks74un"

**Comment by JamesTheClarke** [comment]
Implemented for [Russian Army draft v.1.14.2](/CntoDev/compositions/tree/Russian-Standard-Faction-Update-v1.14.2)
