### ISSUE TITLE
Potential Bug: ACRE2 Channel Presets

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#110]
Today I joined in a TFN Bravo Team and noticed that my default radio channel was set to 1 instead of 2.

We may need to double-check if the A3AA update broke the default channels.

**Comment by Seb105** [comment]
Looks like this was an A3AA feature we missed.

**Comment by Seb105** [comment]
Do you remember what the channels are supposed to be? Obviously Alpha Bravo Charlie are 1 2 3 but I can't remember special elements off the top of my head

**Comment by Seb105** [comment]
Done for TFN and PMC faction in this branch: https://github.com/CntoDev/compositions/tree/Standard-Factions-1.14.2

**Comment by JamesTheClarke** [comment]
Implemented for [Russian Army draft v.1.14.2](/CntoDev/compositions/tree/Russian-Standard-Faction-Update-v1.14.2)

**Comment by JamesTheClarke** [comment]
Implemented for [US Army v.1.14.2](/CntoDev/compositions/tree/US-Army-Standard-Faction-Update-v1.14.2)
