### ISSUE TITLE
RU and US Army Platoon Section: give uniform helmets

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#112]
Originally during the rework of the Standard Factions I aimed at making communications at a distance easier by giving the PLT sections of US Army and RU Army slightly different helmets than the rest of the troops.

However, since deployment, several members approached me about that looking really odd and kinda WW2ish. I agree and thus suggest to change it back to give PLT the same helmets as the rest of the platoon.

**Comment by JamesTheClarke** [comment]
Implemented for Russian draft v.1.14.2

**Comment by Seb105** [comment]
Done for TFN in this branch: https://github.com/CntoDev/compositions/tree/Standard-Factions-1.14.2

**Comment by JamesTheClarke** [comment]
Implemented for [US Army v.1.14.2](/CntoDev/compositions/tree/US-Army-Standard-Faction-Update-v1.14.2)
