### ISSUE TITLE
PLT Sergeant: Removal of AN/PRC-148

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#116]
While updating the RU faction for v1.14.2 I realised that we could save some gear space by removing the 148 from the PLT Sergeant. Currently, the 148 is unnecessary for this role as the PLT sergeant already has access to the 117F in his backpack.

**Comment by Seb105** [comment]
Don't know why it says I linked this issue, I didn't and I'm not fixing it in 1.14.2

**Comment by JamesTheClarke** [comment]
I think you may have clicked on it by accident, it was shown in the description of your pull request: https://github.com/CntoDev/compositions/pull/119

Yeah, postponement it to for v1.14.3 makes sense.

**Comment by enrico-ghidoni** [comment]
Should it be removed from all factions or just the russian one?

**Comment by milivojm** [comment]
All four (TFN, RU, US, PMC)

**Comment by JamesTheClarke** [comment]
Correction: issue not present in PMC Standard faction since they don't have radio backpacks. Relabelling now.
