### ISSUE TITLE
Fireteam Colours have been reset

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#117]
Just noticed that the cnto_additions update has reset all fireteam ST HUD colours to default (white).

Following colours have to be set via attributes:

A1: red
A2: yellow

B1: blue
B2: green

C1: red
C2: yellow

**Comment by JamesTheClarke** [comment]
Implemented for [Russian Army draft v.1.14.2](/CntoDev/compositions/tree/Russian-Standard-Faction-Update-v1.14.2)

**Comment by Seb105** [comment]
Implemented for TFN and PMC

**Comment by JamesTheClarke** [comment]
Implemented for [US Army v.1.14.2](/CntoDev/compositions/tree/US-Army-Standard-Faction-Update-v1.14.2)
