### ISSUE TITLE
New Scopebox Improvements

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#126]
I really like the new Scopebox, it features a lot of functionality and eliminates the need for manual updates regarding new scopes or weapons in the repo. Kudos for that.

However, I played yesterday and noticed a potential improvement: currently all scopes are single coloured in the action menu.

My proposal is to categorize with different colours: e.g. Holo's blue, CCO's green, RDS red etc. just to make the longer list easier to scroll through as a player.

**Comment by Seb105** [comment]
Will be tricky due to implementation, I'll give it a go.
