### ISSUE TITLE
PvP Module - Remove Unit Logo for Vehicles

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#132]
This is something that bothered me for a long time but I always forget posting it because it rarely applies:

Asymmetric PvP missions where players blend into AI groups are very hard to do, especially with vehicles. Because as soon as players jump into a vehicle the yellow owl logo appears on the side of the car making it painfully obvious that these are players trying to pretend to be AI drivers.

It would be great if we had a new PvP module that could be placed down which removes unit logos from all vehicles during a PvP operation.

**Comment by freghar** [comment]
So I've scoured far and wide and I believe this is not possible.

Despite [what the wiki says](https://community.bistudio.com/wiki/Arma_3:_Unit_Insignia#Objects), it's not in `hiddenSelections` nor does `insignia`, `camo`, `squad` or anything similar appear anywhere else in the vehicle config, `p3d` model file or other content files. I've spent an hour searching through the full config of ie. the vanilla Hunter jeep (and RHS USAF CH-47) and couldn't for the live of me find any reference, mention, hint, animation source, texture, proxy reference, anything that could be related.

Just in case the `p3d` encoded strings in its binarized form, I tried de-binarizing it and that indeed worked, here it is, in full glory: [https://i.imgur.com/NeNzGNo.png](https://i.imgur.com/NeNzGNo.png).

So it's hardcoded in the model, both for vanilla and RHS vehicles, and cannot be hidden.

**Comment by freghar** [comment]
To be clear - these are `namedProperties` and can be hidden on Simple Objects using `hideSelection`, but that doesn't work on regular simulated objects.

**Comment by JamesTheClarke** [comment]
Ah man, that's too bad. I was hoping we could find an easy solution for this because there are quite a few neat PvP ideas that would require blending in and are kinda impossible as long as the players are given away by the appearance of their unit logo.

Basically, the only fix is to disable BI Units (or if we'd ever revert back the squad xml) for those kind of PvP missions, correct?

**Comment by JamesTheClarke** [comment]
Closing this issue report due to not being able to implement the requested feature.
