### ISSUE TITLE
Western PMC missing HLC MG3 due to Removal from Main Repo

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#138]
The Western PMC MMG relied on HLC's MG3, but since we removed that mod it means the MMG Gunner spawns without a primary weapon.

**Comment by milivojm** [comment]
I'll label this as wontfix for now since PMC will most likely go down the drain.

**Comment by JamesTheClarke** [comment]
Closing this issue due to MMT dropping the PMC 4th faction: https://www.carpenoctem.co/forums/m/26081621/viewthread/33447259-removal-pmc-faction
