### ISSUE TITLE
set "Player Damage" to 2 (instead of 1) in "Medical Settings [ACE]"

### ISSUE THREAD

**Issue by freghar** [CntoDev/compositions#14]
The Arma 3 engine tracks an overall "damage" value for every object and, independently, hitPart damages for each part of the object. The sum of the latter doesn't always equal the former, but - suffice to say - there's a finite amount of summed "damage" an object can withstand before the engine destroys/kills it.

For example if you shoot a soldier once in each limb (arms/legs) or repeatedly in the same limb, the engine can easily kill the soldier after 2-3 shots (depends on bullet damage, penetration, etc.).

This "Player Damage" setting makes it so that the player soldiers can withstand twice the overall engine damage before being considered killed by the game engine, so that you can be heavily injured in ie. two extremities without being "killed".

**Note that this does not affect the ACE medical system - it doesn't add extra blood or give you extra armor padding to lower the damage. Given two heavy limb injuries, you will bleed out and die within seconds just like before.** This setting only affects the engine's perception of player damage value.

The result from setting it to 2 instead of 1 will be more cases of people going unconscious on limb damage instead of being killed outright. Non-limb damage will also be affected, but the increase from 1 to 2 doesn't bring enough of a difference to be significant on ie. chest or head shots (and again, ACE medical injury seriousness levels, blood amount, pain, etc. are not affected).

Just in case, I've tested the change in several scenarios where a soldier shouldn't survive (sniper shot to the chest, burst fire to the chest, single shot to the head, etc.) and didn't notice any difference. I've also tested it against groups of AI and it did increase my survivability by being able to withstand more wounds in more areas and/or more serious wounds, but - once again - without prompt treatment, I bled to death within a minute or two (if conscious at all).

**Comment by Abuk007** [comment]
That's an interesting way to make medical more viable.
I'm bit worried tho about the possible effects.

This would have to go in line with making AI more dangerous, as already at this point we're killing hundreds of enemies with minimal losses.

Our armor values also have been updated recently to be higher and consistent.

Can we have this setting tested with our faction (TFN) as target for most common ammo types (5.56, 7.62) damage to different body parts (head, chest, legs, arms) from close (~50m) medium (~200m) and far (~400m) ?

I'd like to avoid us becoming bullet sponges while being already deadly efficient, thus punishment being only treatable wounds/limited medical supplies.

**Comment by CNTODachi** [comment]
I think Freghar and Highway have tested some new AI settings which if implemented with this change could really mean we have more injuires on the battlefield instead of deaths and like has been said add to the medical aspects of the game which I think is a positive.

But like Abuk has said the more testing would be required. Not loads just just a bit.

**Comment by CNTODachi** [comment]
After the updated new medical system this is no longer necessary are you happy to close this issue @freghar ?
