### ISSUE TITLE
Convert scopebox to function-based

### ISSUE THREAD

**Issue by Seb105** [CntoDev/compositions#140]
Scopebox going forward will be called via cnto-additions function, All scopeboxes will need updating to simply be the following:

`this call cnto_fnc_scopebox`

Rather than the actual scopebox code itself. Only to be done when Zeus_Enhanced is in the modpack and the version of Arma-additions containing the function is on the repo..

**Comment by Seb105** [comment]
ZEN is now in the repo and this can progress.

**Comment by JamesTheClarke** [comment]
Added standard faction labels because the scopebox is part of each faction composition since v1.14.3.
