### ISSUE TITLE
Use the "Remove ACE Medical EH" module in standard compositions

### ISSUE THREAD

**Issue by freghar** [CntoDev/compositions#141]
https://www.youtube.com/watch?v=ns76iVs18y0

This would allow kills to be properly credited and potentially avoid lag-induced issues by letting the game engine handle damage to enemy AI units instead of ACE doing it via an SQF script.

This module would probably have to be part of each faction composition if you want to retain ACE Medical for civilians and other sides allied to the player side, ie. if the faction is "greenfor", it has side equal to `resistance`, so any enemies would match a condition of
```sqf
(side _this) getFriend resistance < 0.6
```
For other syntax examples, see the tooltip help in the module configuration, or in the video.

**Comment by freghar** [comment]
Alternatively, this could be part of the default module set (Coop at least) and I'm fairly sure it would work reliably, though the condition code won't be as simple as above. Let me know if interested (I seem to remember at least @Shiny-CNTO wanting the functionality provided by this module)

**Comment by Seb105** [comment]
@JamesTheClarke I will implement this and push to your working branch?

**Comment by JamesTheClarke** [comment]
@Seb105 yeah sounds good.

**Comment by Seb105** [comment]
!(_this in playableUnits) is good enough for coop modules rather than per-faction modules right? I don't see why it wouldn't be.

**Comment by freghar** [comment]
> !(_this in playableUnits) is good enough for coop modules rather than per-faction modules right? I don't see why it wouldn't be.

In the comment above, I wanted a bit more complex check that
* works on `playableUnits`, but checks also `allPlayers` and `isPlayer`, to fail safely (leave medical enabled if any of them is true)
* leaves medical enabled for sides allied to all sides occupied by players (a union of the above, but with `getFriend` applied)

**Comment by Seb105** [comment]
I see, yeah we can check that.

We could check if there are _any_ playable units of the side of the created unit when spawning:

`(playableUnits findIf {side _x == side _unit} isEqualTo -1)`

**Comment by freghar** [comment]
More or less,
```sqf
private _players = playableUnits + allPlayers - [objNull];
if (isPlayer _this || _this in _players) exitWith { false };
(_players findIf { side _this getFriend side _x < 0.6 }) != -1;
```
or so.

**Comment by JamesTheClarke** [comment]
To keep a full record of this addition, after brief inputs from @freghar I've removed the new ACE Medical EH module from the PvP default composition in PR #184

""It will not remove the ACE EH from AI units which are friendly to any player, incl. units of the same side, civilians, and any other allied sides.

So if you have ie. BLUFOR vs OPFOR, there will be basically no AI units with medical EH disabled.

Maybe if you make GREENFOR enemy to everybody and use that for AI without having any GREENFOR players. But that's a super corner case""
