### ISSUE TITLE
Uniform Naming Convention of Role Descriptions

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#144]
During the current update process I noticed some minor inconsistencies in the role description naming convention such as:

- some roles were not capitalised while the vast majority of them are capitalised
- the term Assistant is abbreviated with ass. assist. and asst. - using the existing Arma internal abbreviation of asst. makes the most sense

**Comment by freghar** [comment]
> the term Assistant is abbreviated with ass.

Hah, my ancient easter egg discovered!
