### ISSUE TITLE
Replace RHS Flashlights with Vanilla Counterparts

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#147]
The latest Arma Additions light cone functionality for flashlights (near, normal, far) only works for vanilla flashlights.

If we want to utilise it for operations we will have to either replace all flashlights with vanilla counterparts (which could be a problem for RHS Russians) or wait until Arma Additions has included RHS flashlights compatibility into the mod.

**Comment by freghar** [comment]
As advertised elsewhere, the near/normal/far feature works with Russian 2DP flashlights (though not the picatinny-compatible RIS version). As such, there are no changes needed to AK-using factions.

Factions using the `rhsusf_acc_M952V` flashlight should be changed to use the vanila `acc_flashlight`, which shouldn't be a big problem as all weapons using the M952V should also be compatible with vanilla flashlight.

The reason for not extending the feature to M952V is M952V's parent history of a custom AN/PEQ-15 RHS laser/light combo, which uses RHS's own item switching and while I could probably re-define M952V to work like the vanilla flashlight, it's just much easier to use the vanilla flashlight.

**Comment by JamesTheClarke** [comment]
Ah sorry, I must have missed the info regarding the 2DP flashlight.

In that case, we can update TFN and US Army with vanilla flashlights for the next composition update.
