### ISSUE TITLE
Implement Telestation

### ISSUE THREAD

**Issue by Seb105** [CntoDev/compositions#149]
Telestation is now feature complete and should make it into the next cnto-additions barring any issues being discovered. It works like the scopebox, so call the following on any object to get access to it:
`this call cnto_telestation_fnc_ui`

**Comment by Seb105** [comment]
Merged, when modpack updates telestaton can be included.

**Comment by JamesTheClarke** [comment]
@Seb105 is there a rough ETA for the telestation deployment/cnto additions update? If it is somewhat soon I can include it for v2.0.0 otherwise I schedule this issue for a later milestone. ;)
