### ISSUE TITLE
reduce ammo cookoff duration to 20%

### ISSUE THREAD

**Issue by freghar** [CntoDev/compositions#15]
(This does not affect *vehicle* cookoff - the flame effect. This affects only the duration of the ammo explosions after a vehicle or an ammo box fully explodes / is destroyed.)

In the CNTO column of default modules, add a new Execute Code module with these settings:
 * Execute on (MP) = All
 * Exec for JIP players = yes
 * Environment = Unscheduled
 * Run on init = yes
 * Run on respawn = no
 * Keep module = no

The contents should be:
```
/*
 * ACE Settings that don't have a configurable module belong here
 */

/*
 * set vehicle or box ammo cookoff duration to 20%, making it much
 * less annoying while still being fairly dangerous
 */
ace_cookoff_ammoCookoffDuration = 0.2;
```
After copy-pasting, please check that there are no spaces at the end of each line, Arma sometimes does that when copy/pasting.

Also, while I tested the change itself when I made it months ago, the code snipped above is from memory only and not tested to work, please do test it.

**Comment by CNTODachi** [comment]
Have we not already done this our cook off time has already been shortened no?

**Comment by freghar** [comment]
AFAIK no, I proposed it a while ago, but nobody actually put it in the compositions. This change has been done on the liberation mission though - I can't find it in the `.sqm`, but maybe it's in `init.sqf`.

**Comment by CNTODachi** [comment]
I am pretty sure we have just disabled cook off all together now I will look into it though.

**Comment by freghar** [comment]
Unless done elsewhere, this change doesn't exist anywhere in the default module set or in cnto-additions, so we don't currently disable it as far as I'm aware.

Anyway, we might want to hold off with this one for the new ACE 3.12, which changes the config system to use CBA settings, https://github.com/acemod/ACE3/pull/5882/files, and - instead of the variable - call some CBA function that sets it as a mission-wide setting. I'll explore this after I get back from christmas.

We could theoretically have it in the server "profile", but that creates inconsistency between mission and the server it's played on (main, devel, local MP preview), so probably better to do it in the mission.

**Comment by freghar** [comment]
For future reference, that function would be https://github.com/CBATeam/CBA_A3/blob/master/addons/settings/fnc_set.sqf with `_source` set to "mission". This should "work" (as in, not throw an error) even if started without ACE3 as `set` doesn't add the option, `init` does, but if it still errors, see if the setting exists using https://github.com/CBATeam/CBA_A3/blob/master/addons/settings/fnc_get.sqf before trying to set it.

**Comment by Abuk007** [comment]
We still have cook off.  Not sure if 20% is not too drastic tho. Maybe 50% and if its still annoying reduce it further?

**Comment by freghar** [comment]
Back when I was testing it, I used 10% and it was still quite enough (8-12 seconds for a vanilla IFV). It's important to realize that it's 20% of several minutes => still 10-30 seconds of projectiles flying around, depending on ammo left in the vehicle/box.

**Comment by CNTODachi** [comment]
10 to 30 secs sounds good to me.

**Comment by Abuk007** [comment]
Does it affect amount of ammo cooked off during that time?
Example: had 100 shells cooking over 5 min. Now does it emit the same amount over 30 sec? (do we have "brrrrrrrt" effect when condensing the time of cook-off)

**Comment by milivojm** [comment]
Think it just reduces the amount of ammo that is exploding so the sound is still natural.

**Comment by CNTODachi** [comment]
As far as I understand it the value you change is only time amount of ammo is relevant to time so for example you have cook off for 2 mins and 100 explosions then if you reduce to 20% you will have 20 explosions over 24 seconds.

**Comment by Abuk007** [comment]
This is no longer relevant. New ace has cookoff as part of CBA.

**Comment by CNTODachi** [comment]
You mean you can set cook off duration in the settings now?

**Comment by Abuk007** [comment]
Yes, its one of the settings.

**Comment by CNTODachi** [comment]
Then we can close this issue.
