### ISSUE TITLE
Don't use A3AA Locality Transfer module with ACEX Headless

### ISSUE THREAD

**Issue by freghar** [CntoDev/compositions#152]
These two shouldn't really be used together as ACEX Headless does the same thing, except in a more advanced fashion.

https://ace3mod.com/wiki/frameworkx/headless-framework.html

They shouldn't necessarily conflict (when using only one HC), but using both can lead to unexpected behavior - ie. user checking the "don't transfer" checkbox on a group (which is A3AA functionality) while ACEX still does the transfer, because it's using a different variable for disablement (see the link above).

**Comment by JamesTheClarke** [comment]
Just so I know what the exact change is for the next composition update: what exactly would you like changed / removed?

**Comment by freghar** [comment]
As far as I can tell from the `.sqe` file, you are using the `a3aa_ee_locality_transfer` ("Locality transfer (to HC)") editor module. This duplicates functionality provided by ACEX Headless that is enabled by our CBA settings:
```
force force acex_headless_delay = 15;
force force acex_headless_enabled = true;
force force acex_headless_endMission = 0;
force force acex_headless_log = false;
force force acex_headless_transferLoadout = 1;
```
I would suggest removing the "Locality transfer (to HC)" module.
