### ISSUE TITLE
Create platoon ACRE2 channel allocation as a diary entry

### ISSUE THREAD

**Issue by freghar** [CntoDev/compositions#153]
This is about listing which elements use which radio channels.

It's something we've had since the old F3 framework and something I re-created in my additions (with data taken from the "channel list" in each group leader's attributes), but it apparently broke some time ago and when looking at it, I just can't justify the amount of code and runtime overhead (especially on JIP) it would take fixing it, considering the little benefit it brings. So I plan to remove it in the next additions version.

It makes a lot more sense to just create a static page in the diary (inside or outside CNTO TTPs) listing all the elements in order (something I couldn't do) with their radio channels assigned. Technically, this would be done exactly the same way CNTO TTPs are done.

**Comment by JamesTheClarke** [comment]
Very good idea! I'll add it to the todo list for v2.0.0.
