### ISSUE TITLE
HMG Resupply Box is Too Heavy to Drag

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#157]
The HMG Resupply Box is too heavy to even drag, this makes it the only resupply box (aside from the platoon resupply crate) that can't be moved by infantry.

This can slow down mounting up in vehicles more than it needs to. The easiest way to fix this would be to split its current content into two separate HMG resupply boxes: one for the high variant and one for the low variant.

**Comment by baegel49** [comment]
Are you sure its the only one? AFAIK the launcher crate doesn't budge either

**Comment by JamesTheClarke** [comment]
Double checked: launcher crates are fine but mortar crates can also not be dragged. removed one mortar bag from the mortar resupply crate to ensure it can be dragged.
