### ISSUE TITLE
disable freefall altimeter UI

### ISSUE THREAD

**Issue by freghar** [CntoDev/compositions#16]
New ACE3 version 3.12 allows us to disable the "magical" altimeter UI on top of the screen when falling, prior to opening a parachute. This is done via CBA settings and can be set alongside other module-based settings in a mission (more details on this after #12 is resolved).

The idea for this ticket/issue is to use the `hideAltimeter` setting (https://github.com/acemod/ACE3/pull/5836/files#diff-6ad4fc0fb3457bdce9930a74e613a897R25) to hide the UI element, making the player use the ACE-provided "altimeter watch" for precise altitude tracking where necessary, such as for synchronized parachute opening.

**Comment by Abuk007** [comment]
Fine by me. One thing to remember tho is to make loadouts adjusted for this change.

**Comment by Abuk007** [comment]
Is this still a thing? I believe that's sorted out.

**Comment by freghar** [comment]
Yes, https://github.com/CntoDev/cba-settings-lock/blob/23f08d69f81862479d50afdae3cbd0f0a3f55b4b/cba_settings_userconfig/cba_settings.sqf#L48 .
