### ISSUE TITLE
Cold war adaptations

### ISSUE THREAD

**Issue by Seb105** [CntoDev/compositions#160]
Cold war > modern war. 

My suggestion is to add official standard faction adaptation modules that change the faction clothing to a cold war-era alternate, but preserve gear & weapon caliber (so no resupply crate jigging is necessary).

I have created an example for the Russian Army to show what I mean. As it's switching a lot of gear at once, I have included a parity check (making sure items are not lost), you are notified if there are any problems.

https://github.com/CntoDev/compositions/tree/Cold-War-Adaptations

I'd like for this issue to serve as a discussion as to whether this should be officially supported and maintained, and to discuss detials such as exactly how far down the cold war rabbit hole we want to go in terms of removing GPSes, radios etc.

**Comment by Seb105** [comment]
The code is not terribly complicated or hard to maintain. Here's the Russian Army example:
https://pastebin.com/nmA2mcNW

**Comment by baegel49** [comment]
If you want I'll test this on friday. 

As for GPS, radios, etc. I think my Bundeswehr example is a good starting point. No GPS, but long range radios and short ranges for FTLs and SLs. No scopebox either.

**Comment by Seb105** [comment]
So you think that GPSes and radios should be removed with this adaptation? That's fine, it's just worth discussing.

Also, the Russian and US Army weapon swaps are easy and don't require a calibre change, Russians go from AK-74M -> AK-74 (wood), US goes from M4A4/M16A2 -> M16A2. But TFN has no ideal cold war STANAG 5.56, there's good options like the HK33 which are era appropriate and the right calibre but they're a different mag.

**Comment by milivojm** [comment]
If you're aiming for reality, there were no radios on squad level. Platoon had one radio and that's it.  GPS (OMEGA/TRANSIT) definitely was not given to infantry or even tank units. Vehicles however had radios.

**Comment by JamesTheClarke** [comment]
For cold war and lower-tech factions (militias etc.) I usually go for the following setup:

- no gps (except for vehicles)
- radio limitations:
 - either only long-range radios for Element Leaders (PL, SL, support team leaders etc.) - if we go early soviet this would be my preference
 - or long-range radios for Element Leaders plus short-range radios for Element Leaders and FTLs only.
- no NVGs and IR strobes etc.

For Russians, I'd introduce some helmet and vest randomization because until very recently the Russians used a variety of different gear due to shoddy logistics / massive corruption and thus most regiments had non-uniform equipment. To this day their reserve and garrison regiments are still using a wild mix of gear and only the frontline troops have uniform modern EMR equipment.

Regarding how far back the faction should go: I say go big or go home. meaning I'd prefer early cold war gear because that would make both factions feel more distinct and lesst like a colour swap from the standard BLUFOR and OPFOR factions.

**Comment by Seb105** [comment]
I'm not aiming for 100% realism, there's gonna be plenty of anachronisms (like using the PKP over the PKM, modern AT weapons). 

Our standard form for non-modern factions is to take radios away from everyone except element leads which I'd assume we'd do here, which is fine by me. GPS can also be removed. It looks like that is what people want so I can implemnt it.

Like I said, the discussion is around 
a) should this be officially supported
b) the extent of gameplay modifications (current it is just a palette swap)

It appears that gameplay mods such as removing radios is what everyone wants, fine by me.

**Comment by Seb105** [comment]
> For cold war and lower-tech factions (militias etc.) I usually go for the following setup:
> 
>     * no gps (except for vehicles)
> 
>     * radio limitations:
>       -- either only long-range radios for Element Leaders (PL, SL, support team leaders etc.) - if we go early soviet this would be my preference
>       -- or long-range radios for Element Leaders plus short-range radios for Element Leaders and FTLs only.
> 
>     * no NVGs and IR strobes etc.
> 

 Yep. I agree

> 
> For Russians, I'd introduce some helmet and vest randomization because until very recently the Russians used a variety of different gear due to shoddy logistics / massive corruption and thus most regiments had non-uniform equipment. To this day their reserve and garrison regiments are still using a wild mix of gear and only the frontline troops have uniform modern EMR equipment.

Can't be done for vests at least not for the Russians, only a few cold-war era vests are actually big enough to fit all our stuff. Where possible I've used the correct ones tho, medics have the medic one for example.

Helmet randomisation is possible, there isn't as much variety as with the modern ones but I think it can be done. Especially for TFN/US, maybe not for russians.

> 
> Regarding how far back the faction should go: I say go big or go home. meaning I'd prefer early cold war gear because that would make both factions feel more distinct and lesst like a colour swap from the standard BLUFOR and OPFOR factions.

That's fine. Keep in mind body armour is a mid-cold war invention, though.

**Comment by baegel49** [comment]
I would prefer 80s Cold War to 50s/60s, it gives us the option to include radios for FTLs even though its not entirely realistic. 
It does make it a bit more easy to swap from modern gear one week to 80s gear the other, where only riflemen lose their radios (IF we implement that. There's a case to be made to keep radios for everyone as after all its the standard faction idk)

Early Cold War like Korea, Vietnam,  etc. should be reserved for campaigns as it drastically changes gameplay from our standard factions IMO.

There's not much to go with with randomising equipment for the cold war with our modpack.

**Comment by Seb105** [comment]
Personally I'd prefer a 70s/80s erra as well, radios were a tad more prevalant and more importantly body armour was an actual thing. Also, for factions like the US army it means the M16A2 underslung is available. (A1 doesn't have one)

**Comment by baegel49** [comment]
What do you think of giving AARs the M14 battle rifle? to spice it up

**Comment by Seb105** [comment]
This is a standard faction adaptation not a new one. I'm not looking to change the function of any role.
And besides, that would involve implementing checks for each type of role which increases complexity a lot.

**Comment by JamesTheClarke** [comment]
> I'm not aiming for 100% realism, there's gonna be plenty of anachronisms (like using the PKP over the PKM, modern AT weapons).

I fully agree with that approach, I think realism has its place but in Arma gameplay considerations must come first.
 
> Like I said, the discussion is around
> a) should this be officially supported
> b) the extent of gameplay modifications (current it is just a palette swap)

a.) I'm ok with supporting this since it's module based and not an entire faction. A swapper module, especially one that is well made, is much easier to maintain than an entire additional faction (e.g. PMC).

b.) since the swap entails a time period change I think gameplay modifications are more than warranted. we've done that with other time period changes too.


> That's fine. Keep in mind body armour is a mid-cold war invention, though.

Yeah, but lack of body armour is fine for pre-modern armies and militias. It's up to the GM to keep that in mind and adjust enemy force strength accordingly.

**Comment by Seb105** [comment]
Looks like it's supported. I will come back with some new modules then.
a) 1980s ish era (with plenty of anachronisms cause who gives a shit)
b) Body armour for units is a must IMO
c) LR radio distribution unchanged
d) EL/FTLs have SR radios but nobody else
e) No GPS/IR strobes
f) Mag swapping script like-for-like where needed (TFN will probably need this)

Any other requirements people want?

**Comment by baegel49** [comment]
not a requirement, but please give TFN FALs

**Comment by Seb105** [comment]
If the mag size doesn't cause parity failure I will.

**Comment by milivojm** [comment]
Whatever you do, think of gaming impact. :)

If you're just changing skins like for like, you'll probably not get what you want from this.

**Comment by baegel49** [comment]
He literally just posted a shopping list of what will change tho
