### ISSUE TITLE
Improve Repo Documentation

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#162]
Goals Overview:

- [x] shorten ReadMe file to the bare minimum (introduction, links to wiki, license agreement)
- [x] add full license agreement
- [ ] expand wiki with pages for different topics (e.g. how to update compositions, how to maintain repository, how to report issues and deploy releases etc.)

Benefits:

- more formatting options
- wiki updates can be done independent from commits and PRs

**Comment by freghar** [comment]
When you write the wiki about "how to update faction compositions", do include this (in Tools -> Debug Console) just before saving the composition:
```sqf
{
    _x clear3DENAttribute "speaker";
    _x clear3DENAttribute "pitch";
    _x clear3DENAttribute "unitInsignia";
    _x clear3DENAttribute "lambs_danger_disableAI";
} forEach playableUnits;
```
This will clear any "useless" extra attributes that seem to creep in when doing common modifications on the units. The last one may be a one-time thing - it seems it was enabled at some point in the past, and thus is there for ever, even with a 0 ("dont do anything") value.

**Comment by freghar** [comment]
I think I'll instead remove the Identity section of unit attributes (like I used to do before), which will automatically prevent these issues. The downside is that if a MM wants a NPC with specific face or insignia, they'll have to use arsenal (if possible) or scripting commands. But I think that's a reasonable trade-off.

**Comment by JamesTheClarke** [comment]
Hmm, then I'd prefer to keep it a manual step tbh. Your insignia/face attributes are extremely useful and a quick/easy way to enforce faces/races for thematic campaigns (playing as Vietcong for example).

I'd rather keep that in and manually check for the vanilla insignia/identity settings to be empty than lose that functionality.

**Comment by freghar** [comment]
You might have misunderstood.

There's a vanilla "Identity" tab where you can set the name, face, voice, voice pitch, etc., and if you accidentally change any of them, that soldier will have vanilla scripting functions forever attached via attributes, conflicting with my "Extended Gear" tab.

Now, "Extended Gear" works only for players, not for non-player units, so if you're a mission maker and want one specific VIP to have a specific face and maybe insignia, you would have to use the Identity tab, or Arsenal (if it's possible there) or `setFace` / `BIS_fnc_setUnitInsignia` commands manually. I would consider this a fairly rare use case.

If it's indeed possible to set face/insignia in Arsenal, then removing them from the vanilla Identity tab would result in no loss of functionality.

Old cnto-additions had the Identity tab removed for years, and perhaps nobody noticed, so I don't think it would be that big of a deal. But sure, I don't want to remove functionality that MMs might use if I can help it.
