### ISSUE TITLE
Make PLT Sgt loadout exactly the same as PLT Commander.

### ISSUE THREAD

**Issue by Seb105** [CntoDev/compositions#169]
Reasons:
1. PLT Sgt often acts as JTAC/Forward Air Controller, however they cannot mark targets with red smoke UGL and so they need to ask PLT to do it for them.
2. The backpack radio won't be missed to be honest, I've never found it useful, and they'll the backpack space for the extra UGL stuff.
3. This will also fix the overfill issue for Platoon Sergeants regarding the Cold War Modules (they currently lose some smoke grenades)

**Comment by JamesTheClarke** [comment]
Sadly I have to agree. Originally I intended the backpack a.) in case we ever change the radio propagation model again to something more punishing and b.) to make the Sgt visually distinct from the PL so everyone knows at all times who is who.

But unfortunately the radio backpack itself is really not useful so it's probably best to revert back to a regular backpack and a GL.
