### ISSUE TITLE
US Army overfilled units

### ISSUE THREAD

**Issue by Seb105** [CntoDev/compositions#172]
Unit overfills occur when a container is carrying more than it allows. It will cause a unit to lose items upon spawning in. The following units/containers are overfilled in the US Army Faction

- Vehicle Commander Dagger@DAGGER uniform overfilled at 107.5 percent
- Pilot Nightbird@NIGHTBIRD uniform overfilled at 107.5 percent
- Co-Pilot Nightbird uniform overfilled at 107.5 percent
- Jet Pilot Falcon@FALCON uniform overfilled at 107.5 percent
- Game Master@GAME MASTER uniform overfilled at 107.5 percent
- Co-Game Master uniform overfilled at 107.5 percent

I have checked TFN and RUS, they are ok.

The following code will copy a list of units that are overfilled and where to the clipboard when executed from debug console:

```sqf
_overFilled = [];
{
    private _unit = _x;
    private _origLoadUniform = loadUniform _unit;   
    private _origLoadVest = loadVest _unit;   
    private _origLoadBackpack = loadBackpack _unit;  
    private _roleDescription = (_unit get3DENAttribute "description") select 0;  
    if (_origLoadUniform > 1) then      {_overFilled pushBack format ["%1 uniform overfilled at %2 percent", _roleDescription, (loadUniform _unit) * 100];};  
    if (_origLoadVest > 1) then            {_overFilled pushBack format ["%1 vest overfilled at %2 percent", _roleDescription, (loadVest _unit) * 100];};  
    if (_origLoadBackpack > 1) then    {_overFilled pushBack format ["%1 backpack overfilled at %2 percent", _roleDescription, (loadBackpack _unit) * 100];}; 
} forEach playableUnits;
copyToClipBoard str _overFilled;

```

**Comment by JamesTheClarke** [comment]
Very nice catch and script @Seb105 !

I've noticed this too recently, since we tested way back when for container overfill I'm assuming an RHS update at some point changed how much US Army containers can carry (probably to bring it in line with their other factions). Definitely something to be fixed in an upcoming update.

**Comment by freghar** [comment]
You can also use Tools --> A3AA --> Validate Mission, which also checks for overloaded units, amongst other things.

https://www.youtube.com/watch?v=wWKtZHvHcyY&t=1192s
