### ISSUE TITLE
Execute Code Module to set all players initial ACRE2 volume to level 2

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#174]
Currently, the game starts all players on ACRE2 volume level 3 when loading into the map. Depending on the player that volume can carry half across the base which can be very annoying for element leaders when they want to hold their planning briefing and the faffing-about in the background keeps interrupting them.

Having a module that sets everyone to initial volume level 2 could be an effective solution. Level 1 is whisper-volume and thus the players would be far more likely to overcorrect back to level 3 or 4 right away. But level 2 is fairly good for conversational volume without carrying the noise too far.

**Comment by JamesTheClarke** [comment]
@freghar what do you think? Doable or too much effort for what it's worth?

**Comment by freghar** [comment]
Well, if you find out how to do it, then definitely doable.

I quickly looked at:
 * https://github.com/IDI-Systems/acre2/blob/master/addons/sys_gui/fnc_volumeKeyUp.sqf
 * https://github.com/IDI-Systems/acre2/blob/master/addons/sys_gui/fnc_setVoiceCurveLevel.sqf
 * https://github.com/IDI-Systems/acre2/blob/master/addons/api/fnc_setSelectableVoiceCurve.sqf

and all of them seem to apply some internal modifiers, not move the GUI slider itself.

**Comment by JamesTheClarke** [comment]
I've made a feature request on the ACRE2 github: https://github.com/IDI-Systems/acre2/issues/1077

**Comment by JamesTheClarke** [comment]
So ACRE2 dev is open to the idea but basically said that they'd prefer somebody contributed the code for a CBA preset to achieve this: https://github.com/IDI-Systems/acre2/issues/1077

If one of our Arma gods @Seb105 @milivojm @freghar feels like helping ACRE2 to add this to their CBA settings that'd be pretty cool. But this would be a mere nice-to-have, definitely not a high priority feature request.

**Comment by freghar** [comment]
Put this into Execute Code:
```sqf
if (!hasInterface) exitWith {};
waitUntil { !isNil "a3aa_preload_finished" };
[0.4] call acre_api_fnc_setSelectableVoiceCurve;
acre_sys_gui_volumeLevel = 0.25;
```
* execute on MP: all
* exec for JIP: yes
* environment: scheduled
* run on init: yes
* run on respawn: no
* keep module after start: no

(Basically leave all the module settings to defaults.)

**Comment by freghar** [comment]
A more complex version that forces everyone of rank Sergeant and lower to 2/5 volume while inside the base, with a fallback to a one-time setting if the base Location is not present. Once the players leave the base, they can turn up the volume. If they then come back to the base (drive back or respawn), the volume setting is not enforced anymore.
```sqf
if (!hasInterface) exitWith {};
waitUntil { !isNil "a3aa_preload_finished" };
waitUntil { [] call acre_api_fnc_isInitialized };
waitUntil { !isNull player };
if (rankId player >= 3) exitWith {};
if (!isNil "Player_Corpse_CleanUp") then {
    waitUntil {
        if (acre_sys_gui_volumeLevel > 0.25) then {
            [0.4] call acre_api_fnc_setSelectableVoiceCurve;
            acre_sys_gui_volumeLevel = 0.25;
        };
        sleep 0.2;
        !(position player in Player_Corpse_CleanUp);
    };
} else {
    [0.4] call acre_api_fnc_setSelectableVoiceCurve;
    acre_sys_gui_volumeLevel = 0.25;
};
```

**Comment by freghar** [comment]
We might want to limit this (and `boxGuard` too) by mission runtime, ie. unlock boxguard and volume 20 minutes after mission start, just in case the MM forgot to remove these features for base defense missions (where players don't move away from their starting location).

**Comment by freghar** [comment]
> We might want to limit this (and `boxGuard` too) by mission runtime, ie. unlock boxguard and volume 20 minutes after mission start, just in case the MM forgot to remove these features for base defense missions (where players don't move away from their starting location).

I've edited the "more complex" version above to include a simple `time > 1200` check, so this should be ready to be included. I did test the "more complex" version myself, but not with this time addition, so if somebody wants to double-check that ingame, that would be _swell_. ... Otherwise, this is ready to go.
