### ISSUE TITLE
DMT needs to be changed to Sniper Team

### ISSUE THREAD

**Issue by Shiny-CNTO** [CntoDev/compositions#178]
4x acog scope on training map for DMT. Can also be that Churizo did not update compositions no clue. 
4x acog scopes can not be zeroed.

**Comment by JamesTheClarke** [comment]
The scope issue is only present in TFN - Marksman has indeed an ACOG scope unlike the BLUFOR and OPFOR which use proper marksmen scopes.

Another issue: all Spotters do not have a KESTREL device.

**Comment by Seb105** [comment]
The 4x ACOG is intentional, due to the fact that 
* Normal sniper scopes are incompatible with night vision when aiming down sights.
* We used to provide an NVG scope, but it has no reticule at all.

The 4x ACOG used allows for use of NVGs when aiming down sights

**Comment by JamesTheClarke** [comment]
Ah, that makes sense. However, according to Shiny the 4x ACOG is not fully compatible with ACE3 advanced ballistics which makes the scope less usable than its BLUFOR and OPFOR competitors which have proper DMT scopes.

However, with yesterday's decision to change DMT into a bolt-action Sniper Team we'll have to look into new rifle/scope combinations anyways. Thus this issue is somewhat obselete or the fix intent has changed.

**Comment by Shiny-CNTO** [comment]
I thought that's why we give the marksmen another scope in the inventory that is a NVG scope.
Also to add to this, the kestrel needs to also be given to the spotter.
But yes I agree to James that we have to look at a new gun and scope combo anyways. 
Should I open a new card or change this card intend for that? I already tested some weapons and scopes.

**Comment by freghar** [comment]
`optic_NVS` is vanilla, works with any standard weaver rail type weapon (same as MOS - `optic_SOS`) and the same magnification as MOS when zoomed in.

However I'm not sure whether we used to include the NV scope as standard loadout.

**Comment by JamesTheClarke** [comment]
As per March Monthly Meeting decision, the gear of DMT will be swapped from semi-automatic marksman rifle to bolt-action sniper rifle to curb the damage output of DMT. It was the unanimous view of all meeting attendants that currently DMT can take on far too many enemies on its own.

Edited Issue title accordingly.

**Comment by Shiny-CNTO** [comment]
I have started testing some bolt action rifles and will make a case for some rifles over the upcoming week.

**Comment by Seb105** [comment]
Will the scope magnification remain limited?

**Comment by JamesTheClarke** [comment]
> Will the scope magnification remain limited?

We didn't specifically discuss this but since the rate of fire is significantly reduced I think an increase in magnification is fair. If it causes issues it can be reverted again with relatively low efforts.

**Comment by freghar** [comment]
Regarding configs and changes we could do in cnto-additions ...

* Each weapon (from `CfgWeapons`) has a list of magazines (from `CfgMagazines`) it can use. Generally speaking, a weapon doesn't define much else.
* Each magazine (`CfgMagazines`) defines how many bullets are in it, whether they have a tracer effect, how many "tracers every N bullets", how many tracers just before the magazine runs out, etc., but primarily it defines what ammo (from `CfgAmmo`) to use
* Each ammo (`CfgAmmo`) a.k.a. "a bullet", defines how fast it travels, what caliber it is, how much damage it does, how it deflects off surfaces, etc., etc.

This means that if we want to make some sniper rifles stronger (or equivalent to the vanilla M320), we could simply replace the `CfgAmmo` references in the magazines used for those rifles to "point" to the ammo (bullets) used by M320. We might need to adjust the weight of the magazines (for balance reasons or something), but that's doable too. We could also create completely custom new magazines that fit those weapons.

All this is fairly easy possible, but we have to keep in mind mod dependencies - this would make the modification depend on whatever mod we alter, so RHS is probably a safe bet, 3CB we cannot easily modify (they obfuscate everything), NIArsenal should be good too, but weapons from mods like Project OPFOR should be left as-is as there is a non-zero chance we'll switch those mods in the future.

**Comment by freghar** [comment]
> I have started testing some bolt action rifles and will make a case for some rifles over the upcoming week.

Maybe I can give some tips from memory,
* Russians could use the T-5000
* US would use the M107
* TFN maybe the vanilla M320, or (modified, improved) AWMs

Thinking about it, using M320 for TFN would probably negate any need for config-based bullet modification as T-5000 and M107 are plenty strong (from what I remember).

**Comment by freghar** [comment]
> M107 is not bolt action. I tested the M320 and the AWM and their dmg seems to be inferior to some others that are of a lower caliber. Maybe due to the bullet speed.

Indeed, the M320 is an anti-infantry sniper, it can reach 1500m and even 2000m while being semi-accurate. The GM6 Lynx (vanilla .50cal sniper) can't even shoot that far, but is more damaging at closer ranges, making it more of an anti-vehicle (or anti-crew) rifle.
Other modded snipers will probably fall somewhere in this spectrum.

**Comment by JamesTheClarke** [comment]
> M107 is not bolt action. I tested the M320 and the AWM and their dmg seems to be inferior to some others that are of a lower caliber. Maybe due to the bullet speed.

With the deployment of PR #184 and its included fix for issue #141 bolt action rifles should become more lethal as ACE3 damage handlers will be disabled for enemy AI. Will need to be retested and an adequate bolt-action sniper rifle needs to be determined for each of the three standard factions.

**Comment by Shiny-CNTO** [comment]
All guns are tested vs Russian MSV > EMR > Machine Gunner enemies.
All shots are vs the left side chest/arm.

1. M2010 ESR (rhs_weap_XM2010) tested with .300 WM A191 ammo and MK248 MOD 1.
WM a191 ammo took 4 shots.
MK248 MOD 1 took 2 shots.
2. M24 (rhs_weap_m24sws) tested with M993 AP ammo and M118 Ball ammo.
M993 AP took more then 5 shots.
M118 Ball took 4 shots.
3. M40A5 (rhs_weap_m40a5) tested with M993 AP 10 round mags, M62 mags and M118 ball ammo.
M993 AP took 7 shots.
M62 took 7 shots.
M118 took 7 shots.
4. M320 tested both with ace and standard ammo
ace ammo took 4 shots
standard ammo took 2 shots
5. AI AWM (hlc_rifle_awmagnum_bl) Not the M version as that is silenced!! tested with niarms ammo and rhs ammo.
All niarms ammo took more then 7 or 7 shots.
rhs ammo MK248 MOD 1 took 1 or 2 shots.
6. Mosin Nagant (rhs_weap_m38_rail)  5x7.62x54Rmm
took over 10 shots, did not test further.
7. Lee Enfield (uk3cb_enfield_rail) tested with enfield ammo
took 2 shots
8. G29 (BW mod) tested with g29 ammo
took 1 or 2 shots.
be mindful, BW might go away soon.

I think there are 2 clear winners here. The AI AWM and the G29. Both were reliably taking contacts that are heavily armored out with 2 shots max. While others sometimes took even 7 or more.

My recommendation would go to the AI AWM. This is due to it having 6 different models (Black, Tan, Green, and all of those have a ghillie variant). 
I would not suggest a scope replacement. Our scope does it's job and is reliable and easy to read.

Hope this helps!

**Comment by JamesTheClarke** [comment]
As decided in the November Monthly Meeting we will implement the following changes:

- [ ] BluFor: NiArms AWM Rifle
- [ ] IndFor: NiArms AWM Rifle
- [ ] OpFor: RHS T-5000 Rifle
- [ ] Ammo limitation to ca. 50 rounds
