### ISSUE TITLE
I got Task Force Noctem mod and it doesn't load into Zeus.

### ISSUE THREAD

**Issue by EpicflamingChicken** [CntoDev/compositions#183]
I got Task Force Noctem mod and it doesn't load into Zeus for some reason. Is there any way for it to load? I tried restarting my game but it doesn't work.

**Comment by Seb105** [comment]
Hi EpicflamingChicken, Task Force Noctem is the Carpe Noctem main playable faction. It is a composition of playable units placed in the editor, it is not designed to be spawned via Zeus.

**Comment by JamesTheClarke** [comment]
@EpicflamingChicken I assume you mean the Taskforce Noctem standard faction composition, right? https://steamcommunity.com/workshop/filedetails/?id=2430047044

As @Seb105 said it's an EDEN-only composition. Also please keep in mind the composition description _"Note: this composition is highly dependent on the custom modset by Carpe Noctem - Tactical Operations[www.carpenoctem.co] and will not work properly if used outside of the community."_

It is very unlikely you'll get this composition to work as intended without our mods. The Steam release is mainly meant for our Mission Makers so they can quickly download the latest versions of our compositions.
