### ISSUE TITLE
Removal of EpiPens from Non-Medics

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#185]
https://www.carpenoctem.co/forums/page/6/m/26081621/viewthread/33452198-what-do-you-like-or-hate-about-current-medical-system/post/139608992#p139608992

As per April Monthly Meeting decision the EpiPens of all non-medics will have to be removed from all three standard factions.

This change affects every soldier in the composition except medics.

**Comment by freghar** [comment]
You can probably simplify the process by selecting the units you want to be modified and executing
```sqf
{ _x removeItems "ACE_epinephrine" } forEach get3DENSelected "object";
save3DENInventory get3DENSelected "object";
```
