### ISSUE TITLE
VISCOM: Stop hiding players

### ISSUE THREAD

**Issue by Seb105** [CntoDev/compositions#188]
One of params for spectator mode action is "hide player", we should disable this as it is messing up squad order when players enter VISCOM.

**Comment by JamesTheClarke** [comment]
Why is "hide player" in VISCOM in the first place? What the intended use for this param?

**Comment by Seb105** [comment]
Not sure really, it's part of the actual spectator function itself. Normally you'd have to be dead to be a spectator, I guess that's why it's an option.

**Comment by JamesTheClarke** [comment]
If we can ensure it doesn't break anything unintended I'm all for removing the param to avoid the related DUI bug.

@freghar do you see any potential downsides to this?

**Comment by freghar** [comment]
I'm not familiar with what the functionality does, but my guess is that it just tries to prevent 20 player zombies standing around a terminal. Disabling it shouldn't have a significant effect on breaking something else.
