### ISSUE TITLE
Add the "Locality transfer (to HC)" module to Default Modules (Coop)

### ISSUE THREAD

**Issue by freghar** [CntoDev/compositions#191]
Place down the A3AA --> Locality transfer module and leave the default settings in it, then save it to the Coop module composition.

This is the new transfer implementation that should be more compatible and predictable, see https://www.carpenoctem.co/forums/m/26081621/viewthread/33531535-how-to-test-new-better-headless-client-logic .

This change must be done at the same time as https://github.com/CntoDev/cba-settings-lock/issues/46 .

**Comment by JamesTheClarke** [comment]
Probably also adding to PvP for potential missions with neutral AI present.
