### ISSUE TITLE
Utilise ACE Cargo Crate renaming

### ISSUE THREAD

**Issue by Seb105** [CntoDev/compositions#197]
This has not made its way to an ACE release yet, but when it does it will be worth using.
https://github.com/acemod/ACE3/pull/8023

**Comment by JamesTheClarke** [comment]
- [ ] Platoon Supply Crate
- [ ] Fireteam Supply Box
- [ ] Medical Supply Box
- [ ] MAT Supply Box
- [ ] HAT Supply Box
- [ ] Mortar Supply Box
- [ ] HMG Supply Box (high)
- [ ] HMG Supply Box (low)
