### ISSUE TITLE
Silencer Module doesnt add Silencer to DMT Rifle for US Army

### ISSUE THREAD

**Issue by Quantum42** [CntoDev/compositions#198]
Placing down US Army module with Silencer module the DMT rifle doesn't have a silencer added

**Comment by Churizo1** [comment]
`{ 
    private _unit = _x; 
 
   _unit addPrimaryWeaponItem "RH_qdss_nt4";
   _unit addPrimaryWeaponItem "rhs_acc_dtk4short"; 
 
} forEach playableUnits; 
save3DENInventory playableUnits;`

This just tries to add those 2 suppressors. None of our DMT rifles are compatible with either of the two.

A "fix" for this would be to add: 

   _unit addPrimaryWeaponItem "muzzle_snds_b"; 

This adds the vanilla 7.62 mm suppresor. 

Of course, I'm unsure we want to make DMT suppressed by default.

**Comment by JamesTheClarke** [comment]
Went through every standard faction to compare: this is a deliberate design/balance choice. Neither MMG Gunner or the DMT Marksman gets a silencer on their weapon in any of the three Standard Factions.
