### ISSUE TITLE
Don't use "rhs_uniform_m88_patchless" as Russian Gamermaster Uniform

### ISSUE THREAD

**Issue by Seb105** [CntoDev/compositions#199]
This item has a scope of 1, meaning it should not appear in the editor for player use. I guess an RHS update changed it after we started using it.

You can confirm this by switching to another uniform in the editor, saving the loadout, then opening back up the arsenal, "rhs_uniform_m88_patchless" will no longer be an option.

**Comment by JamesTheClarke** [comment]
Checked, they changed class names of several uniforms. I've replaced it with a similar model and updated the composition.
