### ISSUE TITLE
EZ Faction deletes 1x tracer mag from every soldier after first time use.

### ISSUE THREAD

**Issue by baegel49** [CntoDev/compositions#207]
EZ Faction deletes 1x tracer mag from every soldier after first time use. 

Does not seem to be cumulative, using EZ faction again had no effect.

**Comment by JamesTheClarke** [comment]
Quick troubleshooting question: did you swap uniforms, vests and backpacks with EZ-Faction as well? Or did you change uniforms etc. manually and then swap weapons with EZ-Faction?

**Comment by baegel49** [comment]
Fault was on my end, ignore this.
