### ISSUE TITLE
Replace NiArms MP5 with 3CB MP5 for DGR, NB & FLC

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#212]
Due to the removal of the duplicate NiArms MP5s the primary weapons for the following elements have to be replaced with 3CB equivalents:

### BluFor
- [x] Dagger
- [x] Nightbird
- [x] Falcon

### IndFor
- [x] Dagger
- [x] Nightbird
- [x] Falcon

**Comment by freghar** [comment]
You might want to test with at least some ammo variants, RHS MP5 ammo has always been "under-powered", even compared to other 9mm ammo.

**Comment by JamesTheClarke** [comment]
Went with the vanilla 9mm ammo. Wasn't extensive testing on my part but if it causes issues we can swap back to the 3CB ammo.
