### ISSUE TITLE
Rewrite role description

### ISSUE THREAD

**Issue by CptBananaPeel** [CntoDev/compositions#41]
In the standard composition it would be great if we could rewrite the current role description for the vehicle crews, to once without as many quotation marks? 

example given below
---
**current**
description="Vehicle Gunner ""Dagger""";
**new**
description="Vehicle Gunner Dagger";

**Comment by freghar** [comment]
That's how Arma SQF escapes normal `"` sign, it's okay. You're reading the code, not what will appear in the game.

**Comment by milivojm** [comment]
I don't think you understood Freghar. This has to be like that and there is no alternative.

**Comment by CptBananaPeel** [comment]
Its not directly a requirement, as shown in the example below

Current:
`"customID": "jet pilot \"\"falcon\"\"",`

If we changed the role description
`"customID": "jet pilot falcon",`

Its simply just because i like the look of the changed version 😄

**Comment by CNTODachi** [comment]
@CptBananaPeel are you still wishing to make these changes or can you live with you script looking a bit untidy ?

**Comment by CptBananaPeel** [comment]
No need for the changes! 
My bad for forgetting to close the issue.
