### ISSUE TITLE
Add Mortar Supply Crate to Compositions

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#77]
Create a new Supply Crate containing mortar ammo (two bags), a set of map tools and a set of range-charts.

Relevant thread: https://www.carpenoctem.co/forums/m/26081621/viewthread/33152541-add-both-mortar-backpacks-to-standard-resupply

**Comment by JamesTheClarke** [comment]
Will be added after the overhaul release v1.14.0 is complete and rolled out. Already merged TFN Update without this crate and I want to avoid pushing asymmetric faction updates.

But the change is a very simple one and can be completed quickly after the main release.

**Comment by Seb105** [comment]
I used "Basic Weapons Box" for this. As it is similar size but visually distinct from other supply boxes. Do this for other factions too.

**Comment by Seb105** [comment]
Mortars are vehicles. Therefore they can be supplies using vehicle ammo crates or vehicles. The only way to add mortar ammo to a crate would be loads of new mortars. We shouldn't encourage littering.

Therefore we shouldn't do this, and Mission Makers should provide ammo to mortars through vehicle ammo.

**Comment by Seb105** [comment]
Done for TFN and PMC faction in this branch: https://github.com/CntoDev/compositions/tree/Standard-Factions-1.14.2

**Comment by JamesTheClarke** [comment]
Implemented for [Russian Army draft v.1.14.2](/CntoDev/compositions/tree/Russian-Standard-Faction-Update-v1.14.2)

**Comment by JamesTheClarke** [comment]
Implemented for [US Army v.1.14.2](/CntoDev/compositions/tree/US-Army-Standard-Faction-Update-v1.14.2)
