### ISSUE TITLE
jtac adaptation

### ISSUE THREAD

**Issue by milivojm** [CntoDev/compositions#8]
Whoever has the time, trying to create a JTAC adaptation. @CNTODachi please just put here what changes need to be made to platoon rifleman in order to accomplish the JTAC role. I'll see if I can code it.

**Comment by CNTODachi** [comment]
JTAC Requires,

Laser Designator Sand
Designator Batteries x 2 in Vest
PRC 148 Radio in Vest

**Comment by CNTODachi** [comment]
@milivojm this code is better for JTAC no need for backpack it all fits in vest.

{ 
 if (_x get3DENAttribute "description" select 0 == "Platoon Rifleman") then  
 {    
  _x addWeapon "Laserdesignator";   
  _x addItemToVest "ACRE_PRC148";  
  _x addItemToVest "Laserbatteries";  
  _x addItemToVest "Laserbatteries";  
 }; 
} forEach playableUnits; 
 
save3DENInventory playableUnits;

**Comment by CNTODachi** [comment]
Update code as above seen here in e34b75c
