### ISSUE TITLE
Suggestion: Give Platoon leader a helmet

### ISSUE THREAD

**Issue by Seb105** [CntoDev/compositions#82]
Platoon leaders should have a helmet, officers in modern militaries have helmets the same as everyone else.

**Comment by JamesTheClarke** [comment]
Implemented for Russian draft v.1.14.2

**Comment by Seb105** [comment]
Done for TFN and PMC faction in this branch: https://github.com/CntoDev/compositions/tree/Standard-Factions-1.14.2

**Comment by JamesTheClarke** [comment]
Implemented for [us Army v.1.14.2](/CntoDev/compositions/tree/US-Army-Standard-Faction-Update-v1.14.2)
