### ISSUE TITLE
Create a HAT team for standard factions

### ISSUE THREAD

**Issue by baegel49** [CntoDev/compositions#84]
US forces - 2 man Javelin team
TFN - 2 man Javelin team
Russians -  ?

**Comment by JamesTheClarke** [comment]
I suggest to use the vanilla Titan MPRL Compact for the Russian Standard Faction: https://armedassault.fandom.com/wiki/Titan_MPRL_Compact

I couldn't find a more suitable option in our current modpack and unfortunately the more fitting vanilla 9M135 Vorona is a DLC asset (Tanks DLC).
