### ISSUE TITLE
DMT Marksman NVG Scope

### ISSUE THREAD

**Issue by CNTODachi** [CntoDev/compositions#86]
The current TFN NVG scope carried by the marksman does not have a reticle or any means on aiming. I suggest the following scope is used instead AN/PVQ-31A (ARD/Lens Cover).

**Comment by CNTODachi** [comment]
Found out the scopes previously used and mentioned has been removed. I will find a suitable replacement.

**Comment by JamesTheClarke** [comment]
You mean removed from the mod pack?

**Comment by Seb105** [comment]
Replaced scope with suggested one - it hasn't been removed. Removed NVG scope as this new one allows NVG use.

**Comment by Seb105** [comment]
Done for TFN and PMC faction in this branch: https://github.com/CntoDev/compositions/tree/Standard-Factions-1.14.2
