### ISSUE TITLE
Russian Army Sniper has Spotter class

### ISSUE THREAD

**Issue by Seb105** [CntoDev/compositions#94]
Not a massive issue but the other factions are correct.

**Comment by JamesTheClarke** [comment]
I've just done a check through all Standard Factions. This bug is present in all three of them, not just the Russians. All marksmen are either *B_Spotter_F* or *I_Spotter_F* (TFN).

Thus I'm moving the milestone to v1.14.1 to fix all three factions in one go.

**Comment by Seb105** [comment]
Done for TFN and PMC faction in this branch: https://github.com/CntoDev/compositions/tree/Standard-Factions-1.14.2

**Comment by JamesTheClarke** [comment]
Implemented for [Russian Army draft v.1.14.2](/CntoDev/compositions/tree/Russian-Standard-Faction-Update-v1.14.2)

- changed Marksman soldier class from "B_spotter_F" to "O_soldier_M_F"
- changed Spotter soldier class from "B_spotter_F" to "O_spotter_F"

**Comment by JamesTheClarke** [comment]
Implemented for [US Army v.1.14.2](/CntoDev/compositions/tree/US-Army-Standard-Faction-Update-v1.14.2)
- changed Marksman soldier class from "B_spotter_F" to "B_soldier_M_F"
