### ISSUE TITLE
Change the location of LR Radio to backpack

### ISSUE THREAD

**Issue by skaricmate** [CntoDev/compositions#95]
During the mission SL can often go unconscious which can last up to several minutes, depending on the severity of the wound. If a PLT is not right next to the downed SL it can be a while for him to find out what is happening because the next in command of the Squad is unable to retrieve the radio from the uniform of the downed person, unless the person is dead. 

I'm suggesting to change the location of the LR Radio from the uniform to the backpack for all members of the platoon that are in possesion of the LR so in case of the leader going down, next one in the chain of command can immediately retrieve it and inform the PLT lead.

**Comment by Seb105** [comment]
You are able to access the ACE inventory to drag the radio out, however it is not convenient at all.

Realism wise, radios are not kept in the backpack, yet realism wise you should be able to just grab a radio off someone's vest.

I'm in favour of this change, personally.

**Comment by Seb105** [comment]
Done for TFN and PMC faction in this branch: https://github.com/CntoDev/compositions/tree/Standard-Factions-1.14.2

**Comment by JamesTheClarke** [comment]
Implemented for [Russian Army draft v.1.14.2](/CntoDev/compositions/tree/Russian-Standard-Faction-Update-v1.14.2)

**Comment by JamesTheClarke** [comment]
Implemented for [US Army v.1.14.2](/CntoDev/compositions/tree/US-Army-Standard-Faction-Update-v1.14.2)
